cloud_cluster_node:
  ros__parameters:
    publish_frequency: 10.0  # Hz
    cluster_tolerance: 0.15 # cm
    min_cluster_size: 100
    max_cluster_size: 25000
    voxel_leaf_size: 0.03  # reduce voxel size (cm), for better performance
    frame_id: "map"  # refrence frame for node graph
    semantic_pointcloud_topic: "/openfusion/semantic_pointcloud"  # topic for point cloud data