nav2_costmap_2d:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 1.0
    publish_frequency: 1.0
    rolling_window: true
    width: 5.0
    height: 5.0
    resolution: 0.05
    robot_radius: 0.2
    always_send_full_costmap: true

    plugins: ["static_layer", "publisher_layer"]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_subscribe_transient_local: true
      subscribe_to_updates: true

    publisher_layer:
      plugin: "nav2_costmap_2d::CostmapPublisher"
      enabled: true
      topic_name: costmap
