services:
  explorer_container:
    image: ros2/explorer
    build:
      context: ../explorer_ws/.devcontainer
      dockerfile: Dockerfile
    container_name: ros2_explorer_container
    privileged: true
    network_mode: host
    command: /bin/bash
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ../../SAGE/explorer_ws:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_REQUIRE_CUDA: "cuda>=11.3"

  exploitation_container:
    image: ros2/exploitation
    build:
      context: ../exploitation_ws/.devcontainer
      dockerfile: Dockerfile
    container_name: ros2_exploitation_container
    privileged: true
    network_mode: host
    command: /bin/bash
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../../SAGE/exploitation_ws:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_REQUIRE_CUDA: "cuda>=11.3"

  detection_container:
    image: ros2/detection
    build:
      context: ../detection_ws/.devcontainer
      dockerfile: Dockerfile
    container_name: ros2_detection_container
    privileged: true
    network_mode: host
    command: /bin/bash
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../../SAGE/detection_ws:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_REQUIRE_CUDA: "cuda>=11.3"

  lavis_container:
    image: ros2/lavis
    build:
      context: ../lavis_ws/.devcontainer
      dockerfile: Dockerfile
    container_name: ros2_lavis_container
    privileged: true
    network_mode: host
    command: /bin/bash
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../../SAGE/lavis_ws:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_REQUIRE_CUDA: "cuda>=11.3"
      
  isaac-sim:
    image: nvcr.io/nvidia/isaac-sim:4.5.0
    build:
      context: ../isaacsim_4.5.0_ros2_humble/.devcontainer
      dockerfile: Dockerfile
    container_name: isaac-sim
    entrypoint: ["bash"]
    stdin_open: true
    tty: true
    network_mode: "host"
    environment:
      ACCEPT_EULA: "Y"
      PRIVACY_CONSENT: "Y"
      DISPLAY: ${DISPLAY:-}
      QT_X11_NO_MITSHM: "1"
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/isaac-sim/exts/isaacsim.ros2.bridge/humble/lib
    volumes:
      - ${HOME}/docker/isaac-sim/cache/kit:/isaac-sim/kit/cache:rw
      - ${HOME}/docker/isaac-sim/cache/ov:/root/.cache/ov:rw
      - ${HOME}/docker/isaac-sim/cache/pip:/root/.cache/pip:rw
      - ${HOME}/docker/isaac-sim/cache/glcache:/root/.cache/nvidia/GLCache:rw
      - ${HOME}/docker/isaac-sim/cache/computecache:/root/.nv/ComputeCache:rw
      - ${HOME}/docker/isaac-sim/logs:/root/.nvidia-omniverse/logs:rw
      - ${HOME}/docker/isaac-sim/data:/root/.local/share/ov/data:rw
      - ${HOME}/docker/isaac-sim/documents:/root/Documents:rw
      - ../../SAGE/isaacsim_4.5.0_ros2_humble/ros2_ws:/isaac-sim/ros2_ws:rw
    # enable GPUs (recommended) - supported by Docker Compose v2+ / 1.28+
    gpus: all
    # optional fallback for older setups (uncomment if needed)
    # runtime: nvidia
    restart: "no"

  explorer-launcher:
    extends: explorer_container
    container_name: explorer_container
    command: bash -c "cd /app && colcon build && source install/setup.bash && /bin/bash"
    stdin_open: true
    tty: true

  exploitation-launcher:
    extends: exploitation_container
    container_name: exploitation_container
    command: bash -c "cd /app && colcon build && source install/setup.bash && /bin/bash"
    stdin_open: true
    tty: true

  detection-launcher:
    extends: detection_container
    container_name: detection_container
    command: bash -c "cd /app && colcon build && source install/setup.bash && /bin/bash"
    stdin_open: true
    tty: true

  lavis-launcher:
    extends: lavis_container
    container_name: lavis_container
    command: bash -c "cd /app && colcon build && source install/setup.bash && /bin/bash"
    stdin_open: true
    tty: true

volumes:
  ros2_ws:
    driver: local