services:
  explorer_container:
    image: ros2/explorer
    build:
      context: ../explorer_ws/.devcontainer
      dockerfile: Dockerfile
    container_name: ros2_explorer_container
    privileged: true
    network_mode: host
    command: /bin/bash
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ../../SAGE/explorer_ws:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_REQUIRE_CUDA: "cuda>=11.3"

  exploitation_container:
    image: ros2/exploitation
    build:
      context: ../exploitation_ws/.devcontainer
      dockerfile: Dockerfile
    container_name: ros2_exploitation_container
    privileged: true
    network_mode: host
    command: /bin/bash
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../../SAGE/exploitation_ws:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_REQUIRE_CUDA: "cuda>=11.3"

  detection_container:
    image: ros2/detection
    build:
      context: ../detection_ws/.devcontainer
      dockerfile: Dockerfile
    container_name: ros2_detection_container
    privileged: true
    network_mode: host
    command: /bin/bash
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../../SAGE/detection_ws:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_REQUIRE_CUDA: "cuda>=11.3"

  lavis_container:
    image: ros2/lavis
    build:
      context: ../lavis_ws/.devcontainer
      dockerfile: Dockerfile
    container_name: ros2_lavis_container
    privileged: true
    network_mode: host
    command: /bin/bash
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ../../SAGE/lavis_ws:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_REQUIRE_CUDA: "cuda>=11.3"

  # BLIP2 ROS launcher
  blip2-launcher:
    extends: lavis_container
    command: bash -c "cd /app && colcon build && source install/setup.bash && ros2 launch blip2_ros blip2_ros.launch.py"

  detection-launcher:
    extends: detection_container
    command: bash -c "cd /app && colcon build && source install/setup.bash && ros2 launch sage_commander detection_ws.launch.py"

volumes:
  ros2_ws:
    driver: local