image_throttle:
  ros__parameters:
    input_topic: "/depth"
    output_topic: "/depth/throttled"
    timer_frequency: 10.0  # Hz

    resize_enabled: true
    resize_width: 300
    resize_height: 200

    change_gate_enabled: false
    histogram_threshold: 0.9  # lower = more sensitive

    input_qos:
      reliability: "best_effort"
      durability: "volatile"
      history: "keep_last"
      depth: 10

    output_qos:
      reliability: "reliable"
      durability: "volatile"
      history: "keep_last"
      depth: 5
